spring:
  application:
    name: fraline-rest

  datasource:
    url: jdbc:postgresql://localhost:5433/hibernate
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update